import '../styles/About.css';
import React from 'react';

export default function About() {
    return (
        <section className={'container about-page'}>
            <h2>About Us</h2>
            <p>Welcome to Bioinformatics Tools, a hub for powerful and accessible bioinformatics tools designed to support research, education, and discovery in the life sciences.</p>
            <p>We created this platform to make computational biology approachable for everyone — from students and educators to researchers and professionals. Our collection of tools spans a range of core bioinformatics workflows, including:</p>
            <ul className={'about-list'}>
                <li>Motif Finding</li>
                <li>Genome Assembly</li>
                <li>Cyclopeptide Sequencing</li>
            </ul>
            <p>All of our tools are web-based, lightweight, and easy to use — no installations or complicated setup required. Whether you’re running a quick analysis or exploring a dataset in depth, our goal is to provide intuitive interfaces backed by reliable, scientifically validated algorithms.</p>
            <h4 className={'about-subtitle'}>Why We Built This</h4>
            <p>Bioinformatics is advancing rapidly, but many researchers still face barriers when it comes to accessing high-quality computational resources. We aim to bridge that gap by:</p>
            <ul className={'about-list'}>
                <li>Simplifying complex workflows</li>
                <li>Offering transparent, open tools</li>
                <li>Supporting reproducible research</li>
                <li>Promoting accessibility and education</li>
            </ul>
            <h4 className={'about-subtitle'}>Open Science & Collaboration</h4>
            <p>We believe in open science. All of our tools are open-source and freely available for anyone to use, share, or build upon. If you’re a developer or scientist interested in contributing, collaborating, or integrating your own tool into our platform, we’d love to hear from you.</p>
            <br/>
            <p  id={'chatgpt-note'}>Note: This page contains placeholder text generated by ChatGPT.</p>
        </section>
    )
}