tools_list = [
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "frequent_words_mismatch_reverse_complement",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    },
    {
        'popularity': 0,
        'URL': "approximate_pattern_occurrences",
        'imagePath': "/images/favicon.ico",
        'toolTitle': "Approximate Pattern Occurrences",
        'textDescription': "Find all occurrences of a pattern with some mismatches",
        'dateAdded': "2025-05-17T11:14:00",
        'category': "Frequent Pattern Finding",
        'longDescription': 'This tool finds all approximate occurrences of a pattern in a text. This is defined by all patterns with d or less mismatches to the input pattern.',
        'inputFormat': 'distance (d) - the maximum number of mismatches for a string to be considered an approximate occurrence of the input pattern\npattern - the pattern being searched for\ntext - the full text that the pattern is being searched for in',
        'inputExample': '1\nAGGA\nAGGATCGAGATTACTAATGCTAGATATCG\n',
        'hasListArgument': False,
        'listArgumentIndex': -1
    }
]